language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - rbx-19mode
env:
  - DB=sqlite
  - DB=postgresql
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec/
before_script:
  - psql -c 'create database my_app_test' -U postgres
matrix:
  allow_failures:
    - rvm: rbx-19mode
